### ISSUE TITLE
Exclude stage subfolder from version control?

### ISSUE THREAD

**Issue by simonedavico** [benchflow/faban#8]
As far as I understand, the `stage` folder is the build target generated from building with `ant`. Shouldn't we remove it from version control? I see two issues in keeping it:
1. It's useless, since we can build it from source
2. It's annoying, since all the generated files keep showing up as added/modified using `git status`.

What do you think?

**Comment by VincenzoFerme** [comment]
I agree, lets remove it. Do a pull request where you remove the folder.

**Comment by VincenzoFerme** [comment]
Closed by #9
